### ISSUE TITLE
soundbyte

### ISSUE THREAD

**Issue by senolfndk** [DominicMaas/SoundByteOSS#46]
Is the application stopped?

**Comment by DominicMaas** [comment]
Effectively yes, I have tried to make it work again, but API changes alongside lack of time means I just don't have the time to work on this anymore. 

I've written up a summary of everything [here](https://dominicmaas.co.nz/soundbyte-postmortem).

**Comment by senolfndk** [comment]
> Etkili bir şekilde evet, tekrar çalışmasını sağlamaya çalıştım, ancak zaman eksikliğinin yanı sıra API değişiklikleri, artık bunun üzerinde çalışmak için zamanım olmadığı anlamına geliyor.
> 
> [Burada](https://dominicmaas.co.nz/soundbyte-postmortem) her şeyin bir özetini yazdım .

ok
